name = "MatricialMissing"
uuid = "41be38da-c9ad-4b24-9b1b-21c83f144a15"
authors = ["Dante Bertuzzi"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1"

[targets]
test = ["Test"]
